/*
 * SchemaCrawler
 * http://www.schemacrawler.com
 * Copyright (c) 2000-2026, Sualeh Fatehi <sualeh@hotmail.com>.
 * All rights reserved.
 * SPDX-License-Identifier: EPL-2.0
 */

package schemacrawler.utility;

import static java.util.Objects.requireNonNull;
import static us.fatehi.utility.Utility.isBlank;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import schemacrawler.inclusionrule.InclusionRule;
import schemacrawler.inclusionrule.InclusionRuleWithRegularExpression;
import schemacrawler.schema.Column;
import schemacrawler.schema.DatabaseObject;
import schemacrawler.schema.Function;
import schemacrawler.schema.Identifiers;
import schemacrawler.schema.Index;
import schemacrawler.schema.IndexColumn;
import schemacrawler.schema.JavaSqlTypeGroup;
import schemacrawler.schema.PartialDatabaseObject;
import schemacrawler.schema.Procedure;
import schemacrawler.schema.Sequence;
import schemacrawler.schema.Synonym;
import schemacrawler.schema.Table;
import schemacrawler.schema.TableConstraint;
import schemacrawler.schema.TableConstraintColumn;
import schemacrawler.schema.TypedObject;
import schemacrawler.schema.View;
import us.fatehi.utility.UtilityMarker;

@UtilityMarker
public final class MetaDataUtility {

  public enum SimpleDatabaseObjectType {
    unknown,
    table,
    view,
    procedure,
    function,
    synonym,
    sequence;
  }

  private static final List<Pattern> SYSTEM_GENERATED_NAME_PATTERNS =
      List.of(
          Pattern.compile("INTEG_[0-9]+"), // Firebird
          Pattern.compile("CONSTRAINT_[A-Z0-9]+"), // H2
          Pattern.compile("SYS_[FP]K_[0-9]{5}"), // HSQLDB
          Pattern.compile("SQL[0-9]{15}"), // DB2
          Pattern.compile(".+_ibfk_1"), // MySQL, MariaDB
          Pattern.compile("SYS_C.+"), // Oracle
          Pattern.compile(".+_[pf]key"), // PostgreSQL
          Pattern.compile(
              "(FK__[^_]+__[^_]+__[A-Z0-9]+|PK__[^_]+__[A-Z0-9]+|IDX_[^_]+_[^_]+)"), // SQL Server
          Pattern.compile("SCHCRWLR_[A-Z0-9]{8}_[A-Z0-9]{8}")); // SchemaCrawler

  /**
   * Gets a comma-separated list of columns for an index.
   *
   * @param index Index
   * @param identifiers Identifier quoting strategy
   * @return Comma-separated list of columns
   */
  public static String getColumnsListAsString(final Index index, final Identifiers identifiers) {

    requireNonNull(index, "No index provided");
    requireNonNull(identifiers, "No identifier quoting strategy provided");

    final List<IndexColumn> columns = index.getColumns();
    return joinColumns(columns, false, identifiers);
  }

  /**
   * Gets a comma-separated list of columns for an index.
   *
   * @param tableConstraint Table constraint
   * @param identifiers Identifier quoting strategy
   * @return Comma-separated list of columns
   */
  public static String getColumnsListAsString(
      final TableConstraint tableConstraint, final Identifiers identifiers) {

    requireNonNull(tableConstraint, "No table constraint provided");
    requireNonNull(identifiers, "No identifier quoting strategy provided");

    final List<TableConstraintColumn> columns = tableConstraint.getConstrainedColumns();
    return joinColumns(columns, false, identifiers);
  }

  public static SimpleDatabaseObjectType getSimpleTypeName(final DatabaseObject databaseObject) {
    if (databaseObject == null) {
      return SimpleDatabaseObjectType.unknown;
    }
    if (databaseObject instanceof Synonym) {
      return SimpleDatabaseObjectType.synonym;
    }
    if (databaseObject instanceof Sequence) {
      return SimpleDatabaseObjectType.sequence;
    }
    if (databaseObject instanceof Function) {
      return SimpleDatabaseObjectType.function;
    }
    if (databaseObject instanceof Procedure) {
      return SimpleDatabaseObjectType.procedure;
    }
    // NOTE: Check View before Table, since View is a subclass of Table
    if (databaseObject instanceof View) {
      return SimpleDatabaseObjectType.view;
    }
    if (databaseObject instanceof Table) {
      return SimpleDatabaseObjectType.table;
    }
    return SimpleDatabaseObjectType.unknown;
  }

  public static String getTypeName(final DatabaseObject databaseObject) {
    if (databaseObject instanceof final TypedObject<?> typedObject) {
      return typedObject.getType().toString();
    }
    final SimpleDatabaseObjectType simpleTypeName = getSimpleTypeName(databaseObject);
    if (simpleTypeName == SimpleDatabaseObjectType.unknown) {
      return "";
    }
    return simpleTypeName.name();
  }

  /**
   * Checks if a foreign key name is system generated by matching it against known patterns.
   *
   * @param dbObject the foreign key to check
   * @return true if the name matches any of the patterns, false otherwise
   */
  public static boolean hasSystemGeneratedName(final DatabaseObject dbObject) {
    if (dbObject == null || dbObject.getName().isEmpty()) {
      return false;
    }
    for (final Pattern pattern : SYSTEM_GENERATED_NAME_PATTERNS) {
      if (pattern.matcher(dbObject.getName()).matches()) {
        return true;
      }
    }
    return false;
  }

  public static String inclusionRuleString(final InclusionRule inclusionRule) {
    String inclusionRuleString = ".*";
    if (inclusionRule instanceof final InclusionRuleWithRegularExpression expression) {
      final String schemaInclusionPattern = expression.getInclusionPattern().pattern();
      if (!isBlank(schemaInclusionPattern)) {
        inclusionRuleString = schemaInclusionPattern;
      }
    }
    return inclusionRuleString;
  }

  public static boolean isPartial(final DatabaseObject databaseObject) {
    return databaseObject == null || databaseObject instanceof PartialDatabaseObject;
  }

  public static boolean isView(final Table table) {
    return table instanceof View;
  }

  public static String joinColumns(
      final List<? extends Column> columns,
      final boolean omitLargeObjectColumns,
      final Identifiers identifiers) {

    requireNonNull(columns, "No columns provided");
    requireNonNull(identifiers, "No identifiers provided");

    final List<String> columnsList = new ArrayList<>();
    for (int i = 0; i < columns.size(); i++) {
      final Column column = columns.get(i);
      if (!column.isColumnDataTypeKnown()) {
        continue;
      }
      final JavaSqlTypeGroup javaSqlTypeGroup =
          column.getColumnDataType().getJavaSqlType().getJavaSqlTypeGroup();
      if (!omitLargeObjectColumns
          || javaSqlTypeGroup != JavaSqlTypeGroup.large_object
              && javaSqlTypeGroup != JavaSqlTypeGroup.object) {
        columnsList.add(identifiers.quoteName(column.getName()));
      }
    }
    return String.join(", ", columnsList);
  }

  private MetaDataUtility() {
    // Prevent instantiation
  }
}
